# List of blocks and their corresponding maximum minecart speeds
# Blocks must be from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# The default minecart speed is 0.4
default-speed: 2.0
blocks:
  COARSE_DIRT: 0.4
  SOUL_SAND: 0.2